app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path: /
    defaults:
      _controller: "AppBundle:Default:index"

services:
    path: /services
    defaults:
      _controller: "AppBundle:Default:services"